---
- name: Converge
  hosts: all
  gather_facts: true
  become: true

  vars:
    install_root: /opt/IBM
    install_src: /opt/install
    ibm_user: wasuser
    iim_installerpackage: /mnt/d/software/agent.installer.linux.gtk.x86_64_1.9.1003.20200730_2125.zip

  roles:
    - role: stoeps13.ansible-role-iim
