---
# Verify playbook
- name: Verify
  hosts: all
  tasks:
    - name: Get the version of an IIM already installed
      become: true
      become_user: "{{ __iim_user }}"
      shell:
        grep version ~{{ __iim_user }}/etc/.ibm/registry/InstallationManager.dat | cut -d= -f2
      ignore_errors: true
      changed_when: false
      register: installed

    - name: Test if IIM is installed and version >= {{ __iim_version }}
      assert:
        that:
          - (installed.stdout is version_compare(__iim_version, '>=')
